version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          record: true
scheduled-workflow:
  triggers:
    - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only: -fubsisu
